config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :leagues

  resources :locations

  resources :teams

  resources :game_events

  root 'welcome#index'

end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :teams
	has_many :game_events
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @team = Team.all
    @game_events = GameEvent.all
    @leagues = League.all
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
    @team = Team.all
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :league, :sport, :start_date, :end_date)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<header>
  <h1>New League</h1>
</header>

<div class="body-wrap league-edit">
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="back-btn edit-btn edit-submit">
    <%= f.submit %>
  </div>
  <table>
    <tr>
      <td>
        <%= f.label :name %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
      <td>
        <%= f.label :sport %>
      </td>
      <td>
        <%= f.text_field :sport %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :start_date %>
      </td>
      <td>
        <%= f.text_field :start_date %>
      </td>
      <td>
        <%= f.label :end_date %>
      </td>
      <td>
        <%= f.text_field :end_date %>
      </td>
    </tr>
  </table>
<% end %>
</div>

app/views/leagues/edit.html.erb
<header>
	<h1><%= @league.name %></h1>
	<h4><%= @league.sport %></h4>
</header>

<div class="body-wrap league-edit">
	<div class="back-btn">
		<%= link_to 'Back', @league %>
		<br>
	</div>
	<div class="left-half">
		<h3 class="inline-me">Edit League Information</h3>
		<%= render 'form' %>
	</div>
	<div class="right-half">
		<h3 class="inline-me">Teams in League</h3>
		<div class="view-league-btn">
			<%= link_to 'Add Team', new_team_path %>
		</div>
		<div class="clearfix"></div>
		<% @team.each do |team| %>
			<p style="width: 45%; float: left;"><%= team.name %></p>
		<% end %>
	</div>
</div>

app/views/leagues/index.html.erb
<header>
  <h1 style="text-align: center;">Leagues</h1>
  <a href="" class="personal-profile-link">Welcome, Thomas</a>
</header>
<div class="body-wrap league-index">
  <div class="back-btn edit-btn">
      <%= link_to 'New League', new_league_path %>
  </div>
  <div class="special-top black-bg">
    <table>
        <tr>
          <th>Name</th>
          <th>Sport</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th><th>
        </tr>
    </table>
  </div>
    <table class='league-schedule'>
        <% @leagues.each do |league| %>
          <tr>
            <td><%= league.name %></td>
            <td><%= league.sport %></td>
            <td><%= league.start_date %></td>
            <td><%= league.end_date %></td>
            <td>
              <div class="view-league-btn">
                <%= link_to 'View League', league %>
              </div>
            </td>
            <!-- <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
    </table>
  </table>
</div>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

 <div class="back-btn">
    <%= link_to 'Back', leagues_path %>
  </div>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>
<a href="javascript:window.print()">Print Schedule</a>

<header>
	<h1 style="text-align: center;"><%= @league.name %></h1>
	<h4 style="text-align: center;"><%= @league.sport %></h4>
</header>
<div class="body-wrap">
	<div class="back-btn">
		<%= link_to 'Back', leagues_path %>
	</div>
	<div class="back-btn edit-btn">
		<%= link_to 'Edit League Info', edit_league_path(@league) %>
	</div>

	<div class="back-btn edit-btn left-first-btn">
		League Standings
	</div>

	<div class="back-btn edit-btn left-second-btn">
		Button Two
	</div>

	<div class="special-top black-bg border-box">
		<div class="one-third-width">
		  <strong>Name:</strong> <%= @league.name %>
		  	<br>
		  <strong>Sport:</strong> <%= @league.sport %>
		</div>
		<div class="one-third-width border-box">
		 <strong>Start Date:</strong>
		  <%= @league.start_date %>
		  	<br>
		  <strong>End Date:</strong>
		  <%= @league.end_date %>
		</div>
		<div class="one-third-width border-box">
			<strong>Teams:</strong>

			
			<% @team.each do |team| %>
				<% if team.league_id == @league.id %>
					<%= link_to team.name, team %> 
					, 
				<% end %>	
			<% end %>

		</div>
	</div>

	<section id="new-game">
	<table>
	  <thead>
	    <tr>
	      <th>Home</th>
	      <th>Away</th>
	      <th>Game Time</th>
	      <th>Location</th>
	      <th>Home Score</th>
	      <th>Away Score</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @game_events.each do |game_event| %>
   			 <% if game_event.league_id == @league.id %>
				 <tr>
			        <td><%= link_to game_event.home_team.name, game_event.home_team %></td>
			        <td><%= link_to game_event.away_team.name, game_event.away_team %></td>
			        <td><%= game_event.start_date %></td>
			        <td><%= game_event.location %></td>
			        <td><%= game_event.home_score %></td>
			        <td><%= game_event.away_score %></td>
			        <td><%= link_to 'Show', game_event %></td>
			        <td><%= link_to 'Edit', edit_game_event_path(game_event) %></td>
			        <td><%= link_to 'Destroy', game_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			      </tr>
			<% end %>
	    <% end %>
	  </tbody>
	</table>
	<br>

	<div class="new-game-link"><%= link_to 'Add New Game', new_game_event_path %></div>
	</div>
	</section>
</div>