config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :leagues

  resources :locations

  resources :teams

  resources :game_events

  root 'welcome#index'

end

app/models/game_event.rb
class GameEvent < ActiveRecord::Base
	belongs_to :home_team, class_name: 'Team', foreign_key: :home_team_id
	belongs_to :away_team, class_name: 'Team', foreign_key: :away_team_id
	belongs_to :league
end

app/controllers/game_events_controller.rb
class GameEventsController < ApplicationController
  before_action :set_game_event, only: [:show, :edit, :update, :destroy]

  # GET /game_events
  # GET /game_events.json
  def index
    @game_events = GameEvent.all
  end

  # GET /game_events/1
  # GET /game_events/1.json
  def show
  end

  # GET /game_events/new
  def new
    @game_event = GameEvent.new
    @leagues = League.all
  end

  # GET /game_events/1/edit
  def edit
    @leagues = League.all
  end

  # POST /game_events
  # POST /game_events.json
  def create
    @game_event = GameEvent.new(game_event_params)

    respond_to do |format|
      if @game_event.save
        format.html { redirect_to @game_event, notice: 'Game event was successfully created.' }
        format.json { render :show, status: :created, location: @game_event }
      else
        format.html { render :new }
        format.json { render json: @game_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_events/1
  # PATCH/PUT /game_events/1.json
  def update
    respond_to do |format|
      if @game_event.update(game_event_params)
        format.html { redirect_to @game_event, notice: 'Game event was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_event }
      else
        format.html { render :edit }
        format.json { render json: @game_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_events/1
  # DELETE /game_events/1.json
  def destroy
    @game_event.destroy
    respond_to do |format|
      format.html { redirect_to game_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_event
      @game_event = GameEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_event_params
      params.require(:game_event).permit(
        :title, :start_date, :end_date, :location,
        :home_team_id, :away_team_id, :home_score, :away_score, :league_id
      )
    end
end

app/helpers/game_events_helper.rb
module GameEventsHelper
end

app/views/game_events/_form.html.erb
<%= form_for(@game_event) do |f| %>
  <% if @game_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_event.errors.count, "error") %> prohibited this game_event from being saved:</h2>

      <ul>
      <% @game_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table>
  <tr>
    <td colspan="6">
      <%= f.label :title %> <%= f.text_field :title %>
    </td>
  </tr>
  <tr>
    <td> Home: <br><%= f.collection_select :home_team_id, Team.all, :id, :name, :include_blank => true %></td>
    <td>
      <%= f.label :home_score %><br>
      <%= f.text_field :home_score %>
    </td>
  </tr>
  <tr>
    <td>
     Away: <br><%= f.collection_select :away_team_id, Team.all, :id, :name, :include_blank => true %>
    </td>
    <td>
      <%= f.label :away_score %><br>
      <%= f.text_field :away_score %>
    </td>
  </tr>
  <tr>
    <td colspan="3">
      <%= f.label :start_date %><br>
      <%= f.datetime_select :start_date, :include_blank => true %></td>
    <td colspan="3">
      <%= f.label :location %><br>
      <%= f.text_area :location %>
    </td>
  </tr>
</table>
   <%= f.collection_select :league_id, @leagues, :id, :name, :include_blank => true %>
 <!--  <div class="field">
   
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div> -->
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_events/edit.html.erb
<h1>Editing game_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_event %> |
<%= link_to 'Back', game_events_path %>

app/views/game_events/index.html.erb
<section id="new-game">
<h1>2014 NCAA Schedule</h1>

<table>
  <thead>
    <tr>
      <th>Home</th>
      <th>Away</th>
      <th>Game Time</th>
      <th>Location</th>
      <th>Home Score</th>
      <th>Away Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_events.each do |game_event| %>
      <tr>
        <td><%= link_to game_event.home_team.name, game_event.home_team %></td>
        <td><%= link_to game_event.away_team.name, game_event.away_team %></td>
        <td><%= game_event.start_date %></td>
        <td><%= game_event.location %></td>
        <td><%= game_event.home_score %></td>
        <td><%= game_event.away_score %></td>
        <td><%= link_to 'Show', game_event %></td>
        <td><%= link_to 'Edit', edit_game_event_path(game_event) %></td>
        <td><%= link_to 'Destroy', game_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<a href="javascript:window.print()">Print Schedule</a>
<br>

<div class="new-game-link"><%= link_to 'Add New Game', new_game_event_path %></div>
</div>
</section>

app/views/game_events/new.html.erb
<h1>Add New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', game_events_path %>

app/views/game_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game_event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @game_event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @game_event.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @game_event.location %>
</p>

<p>
  <strong>Home team:</strong>
  <%= @game_event.home_team.name %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game_event.away_team.name %>
</p>
<p>
  <strong>Home Score</strong>
  <%= @game_event.home_score %>
</p>
<p>
  <strong>Away Score</strong>
  <%= @game_event.away_score %>
</p>

<%= link_to 'Edit', edit_game_event_path(@game_event) %> |
<%= link_to 'Back', game_events_path %>